# Generated by Django 4.1.2 on 2022-10-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_22sm',
            field=models.IntegerField(default=0, verbose_name='Price_22sm'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_26sm',
            field=models.IntegerField(default=0, verbose_name='Price_26sm'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_32sm',
            field=models.IntegerField(default=0, verbose_name='Price_32sm'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pizzaapp.sizes', verbose_name='Size'),
        ),
    ]
